# Generated by Django 5.0 on 2025-11-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_range', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=10)),
                ('place_of_living', models.CharField(max_length=100)),
                ('first_appearance', models.CharField(max_length=10)),
            ],
        ),
    ]
