# Generated by Django 5.0 on 2025-11-22 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='age_range',
            new_name='AgeRange',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='first_appearance',
            new_name='FirstAppearance',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='genre',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='occupation',
            new_name='Occupation',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='place_of_living',
            new_name='PlaceOfLiving',
        ),
        migrations.AlterModelTable(
            name='character',
            table='CHARACTER',
        ),
    ]
